# Generated by Django 5.2.17 on 2026-09-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Set when an office issues a temporary password. Cleared once the person picks their own.'),
        ),
    ]
