# Generated by Django 5.2.17 on 2026-09-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('bn', 'বাংলা')], help_text="Blank follows the school's default language.", max_length=5),
        ),
    ]
