# Generated by Django 5.2.17 on 2026-09-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='sms_opt_in',
            field=models.BooleanField(default=True, help_text='Clear this when a family asks not to be texted.', verbose_name='Receive SMS'),
        ),
    ]
