# Generated by Django 5.2.17 on 2026-09-23 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_subject_plan_and_sections'),
        ('students', '0004_one_primary_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='chosen_subjects',
            field=models.ManyToManyField(blank=True, help_text='Choice subjects taken as main subjects.', related_name='chosen_by', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='fourth_subject',
            field=models.ForeignKey(blank=True, help_text='The optional 4th subject. It can raise the GPA but never fail the student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fourth_subject_of', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='group',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('business', 'Business Studies'), ('humanities', 'Humanities')], max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='Place of birth'),
        ),
        migrations.AddField(
            model_name='student',
            name='board_registration_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='Board registration no.'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, verbose_name="Father's name"),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name_bn',
            field=models.CharField(blank=True, max_length=150, verbose_name="Father's name (Bangla)"),
        ),
        migrations.AddField(
            model_name='student',
            name='father_nid',
            field=models.CharField(blank=True, max_length=17, verbose_name="Father's NID"),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, verbose_name="Mother's name"),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name_bn',
            field=models.CharField(blank=True, max_length=150, verbose_name="Mother's name (Bangla)"),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_nid',
            field=models.CharField(blank=True, max_length=17, verbose_name="Mother's NID"),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, default='Bangladeshi', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_registration_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='Previous registration no.'),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_roll',
            field=models.CharField(blank=True, max_length=20, verbose_name='Previous class roll'),
        ),
        migrations.AddField(
            model_name='student',
            name='unique_id',
            field=models.CharField(blank=True, help_text='The government student ID.', max_length=30, verbose_name='Student unique ID'),
        ),
    ]
