# Generated by Django 5.2.17 on 2026-09-23 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ib_diploma'),
        ('students', '0005_board_identity_and_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('transfer', 'Transfer certificate'), ('leaving', 'School leaving certificate'), ('character', 'Character certificate (testimonial)')], max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], default='en', max_length=2)),
                ('serial', models.CharField(max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(blank=True, max_length=20)),
                ('verification_code', models.UUIDField(editable=False, unique=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=200)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('replaces', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by', to='students.certificate')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('school', 'serial'), name='unique_certificate_serial')],
            },
        ),
    ]
