# Generated by Django 5.2.17 on 2026-09-24 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_privacy_baseline'),
        ('students', '0007_result_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('records', "Keeping and using the child's school records"), ('sms', 'Text messages about the child'), ('photos', 'Photos of the child in school publications'), ('abroad', 'Sharing entry and result data with awarding bodies outside Bangladesh'), ('sensitive', 'Sharing health or access-arrangement information with an awarding body')], max_length=10)),
                ('given', models.BooleanField(help_text='Ticked for consent given, clear for consent refused or withdrawn.')),
                ('method', models.CharField(choices=[('form', 'Signed form'), ('portal', 'Family portal'), ('other', 'Other (recorded by staff)')], default='form', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='students.student')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['student', 'purpose'], name='students_gu_student_c977ee_idx')],
            },
        ),
    ]
