# Generated by Django 5.2.17 on 2026-09-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_privacy_baseline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='kind',
            field=models.CharField(choices=[('transfer', 'Transfer certificate'), ('leaving', 'School leaving certificate'), ('character', 'Character certificate (testimonial)'), ('study', 'Studentship certificate')], max_length=10),
        ),
    ]
