# Generated by Django 5.2.17 on 2026-09-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentship_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianconsent',
            name='method',
            field=models.CharField(choices=[('form', 'Signed form'), ('portal', 'Family portal'), ('application', 'Given with the admission application'), ('other', 'Other (recorded by staff)')], default='form', max_length=12),
        ),
    ]
