# Generated by Django 5.2.17 on 2026-09-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Clear this to retire the record without losing the history that uses it.'),
        ),
        migrations.AddField(
            model_name='designation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Clear this to retire the record without losing the history that uses it.'),
        ),
    ]
