# Generated by Django 5.2.17 on 2026-09-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_deactivatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='category',
            field=models.CharField(choices=[('cv', 'CV'), ('academic', 'Academic qualification'), ('other', 'Other document')], default='other', max_length=10),
        ),
    ]
