# Generated by Django 5.2.17 on 2026-09-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(help_text='Used for the subdomain later, e.g. dhaka-model', unique=True)),
                ('eiin', models.CharField(blank=True, help_text='Bangladesh institution ID', max_length=10, verbose_name='EIIN')),
                ('motto', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='school/logos/')),
                ('principal_name', models.CharField(blank=True, max_length=150)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('currency_symbol', models.CharField(default='৳', max_length=5)),
                ('country', models.CharField(default='BD', max_length=2)),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=50)),
                ('weekend_days', models.CharField(default='5,6', max_length=20)),
                ('sms_sender_id', models.CharField(blank=True, max_length=20)),
                ('sms_api_url', models.URLField(blank=True, help_text='Gateway endpoint, e.g. https://bulksmsbd.net/api/smsapi')),
                ('sms_api_key', models.CharField(blank=True, max_length=200)),
                ('sms_extra_params', models.CharField(blank=True, help_text='Extra query params as key=value&key2=value2', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
