# Generated by Django 5.2.17 on 2026-09-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='staff_self_checkin',
            field=models.BooleanField(default=False, help_text='Let teachers and staff record their own arrival and departure.'),
        ),
    ]
