# Generated by Django 5.2.17 on 2026-09-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_leave_attendance_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='notify_absence_sms',
            field=models.BooleanField(default=False, verbose_name='Tell guardians about an absence'),
        ),
        migrations.AddField(
            model_name='school',
            name='notify_admission_sms',
            field=models.BooleanField(default=False, verbose_name='Welcome newly admitted students'),
        ),
        migrations.AddField(
            model_name='school',
            name='notify_due_sms',
            field=models.BooleanField(default=False, verbose_name='Allow fee reminder SMS'),
        ),
        migrations.AddField(
            model_name='school',
            name='notify_payment_sms',
            field=models.BooleanField(default=False, verbose_name='Confirm fee payments by SMS'),
        ),
        migrations.AddField(
            model_name='school',
            name='notify_results_sms',
            field=models.BooleanField(default=False, verbose_name='Announce published results'),
        ),
    ]
