# Generated by Django 5.2.17 on 2026-09-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='late_fee_cap',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Most that may be charged on one invoice. Zero means no cap.', max_digits=10),
        ),
        migrations.AddField(
            model_name='school',
            name='late_fee_per_day',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Charged for each day an invoice is overdue. Zero disables late fees.', max_digits=8),
        ),
    ]
