# Generated by Django 5.2.17 on 2026-09-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_late_fee_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='books_locked_until',
            field=models.DateField(blank=True, help_text='Nothing may be posted on or before this date. Set it once a month has been reported on.', null=True),
        ),
    ]
