# Generated by Django 5.2.17 on 2026-09-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_period_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='sibling_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Taken off every younger sibling's fees when two or more children share a primary guardian. The eldest pays in full. Zero switches it off.", max_digits=5),
        ),
    ]
