# Generated by Django 5.2.17 on 2026-09-23 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sibling_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='sibling_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Taken off every younger sibling's fees when two or more children share a primary guardian. The eldest pays in full. Zero switches it off. 0 to 100.", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.CheckConstraint(condition=models.Q(('sibling_discount_percent__gte', 0), ('sibling_discount_percent__lte', 100)), name='sibling_discount_is_a_percentage'),
        ),
    ]
