# Generated by Django 5.2.17 on 2026-09-23 03:36

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sibling_discount_bounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='sms_api_url',
            field=core.models.HttpsURLField(blank=True, help_text='Gateway endpoint, e.g. https://bulksmsbd.net/api/smsapi'),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=core.models.HttpsURLField(blank=True),
        ),
    ]
