# Generated by Django 5.2.17 on 2026-09-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_https_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='assessment_system',
            field=models.CharField(choices=[('own', "School's own rules (percentage and grade)"), ('national', 'Bangladesh national curriculum (SSC board rules)')], default='own', help_text='The rules results are calculated by. A class can override this, for a school that runs both a national-curriculum and an English-medium stream.', max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='bangla_enabled',
            field=models.BooleanField(default=True, help_text='Lets each person switch the screens to Bangla.', verbose_name='Offer the Bangla interface'),
        ),
        migrations.AddField(
            model_name='school',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা')], default='en', help_text='What people see until they choose for themselves.', max_length=5),
        ),
        migrations.AddField(
            model_name='school',
            name='payment_gateway',
            field=models.CharField(choices=[('none', 'Off'), ('sslcommerz', 'SSLCommerz (bKash, Nagad, Rocket, cards, banks)'), ('demo', 'Demonstration (no money moves)')], default='none', max_length=12),
        ),
        migrations.AddField(
            model_name='school',
            name='public_results_enabled',
            field=models.BooleanField(default=False, help_text='Families can look up a published result with the student ID and date of birth, without signing in.', verbose_name='Publish results online'),
        ),
        migrations.AddField(
            model_name='school',
            name='sslcommerz_sandbox',
            field=models.BooleanField(default=True, help_text='Clear this only with live credentials.', verbose_name='Use the SSLCommerz sandbox'),
        ),
        migrations.AddField(
            model_name='school',
            name='sslcommerz_store_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='SSLCommerz store ID'),
        ),
        migrations.AddField(
            model_name='school',
            name='sslcommerz_store_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='SSLCommerz store password'),
        ),
    ]
