# Generated by Django 5.2.17 on 2026-09-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_more_rulebooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='assessment_system',
            field=models.CharField(choices=[('own', "School's own rules (percentage and grade)"), ('national', 'Bangladesh national curriculum (SSC board rules)'), ('cambridge', 'Cambridge (IGCSE, O Level, AS and A Level)'), ('edexcel', 'Pearson Edexcel (International GCSE, International AS and A Level)'), ('ib_myp', 'IB Middle Years Programme (criteria to grades 1-7)'), ('ib_dp', 'IB Diploma Programme (grades 1-7, core points, diploma conditions)')], default='own', help_text='The rules results are calculated by. A class can override this, for a school that runs both a national-curriculum and an English-medium stream.', max_length=10),
        ),
    ]
