# Generated by Django 5.2.17 on 2026-09-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_result_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='retention_years',
            field=models.PositiveSmallIntegerField(default=7, help_text='Years after a student leaves before their personal data may be erased. Fee and accounting records are kept either way, without the personal details.'),
        ),
    ]
