# Generated by Django 5.2.17 on 2026-09-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_privacy_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='register_edit_days',
            field=models.PositiveSmallIntegerField(default=0, help_text="After this many days only the school's managers can change a register. 0 keeps registers open to teachers.", verbose_name='Days a register stays open to teachers'),
        ),
        migrations.AddField(
            model_name='school',
            name='register_takers',
            field=models.CharField(choices=[('section_teachers', 'Class teacher, or any teacher of the section as cover'), ('class_teacher', 'Class teacher only')], default='section_teachers', help_text="The school's managers can always take a register.", max_length=16, verbose_name='Who takes the daily register'),
        ),
    ]
