# Generated by Django 5.2.17 on 2026-09-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_register_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admissions_enabled',
            field=models.BooleanField(default=False, help_text='Set by the platform administrator only.', verbose_name='Online admissions module'),
        ),
        migrations.AddField(
            model_name='school',
            name='homework_enabled',
            field=models.BooleanField(default=False, help_text='Set by the platform administrator only.', verbose_name='Homework module'),
        ),
    ]
