# Generated by Django 5.2.17 on 2026-09-24 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_school_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='homework_files_months',
            field=models.PositiveSmallIntegerField(default=6, help_text='How long after the academic year ends the photos and files students handed in are kept.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Keep homework files for (months)'),
        ),
    ]
