# Generated by Django 5.2.17 on 2026-09-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_school_homework_files_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='notify_homework_sms',
            field=models.BooleanField(default=False, help_text='Once a week, one message per child with homework not handed in, to the guardian the school would ring.', verbose_name='Weekly homework digest'),
        ),
    ]
