# Generated by Django 5.2.17 on 2026-09-24 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_school_notify_homework_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admissions_keep_months',
            field=models.PositiveSmallIntegerField(default=6, help_text='How long after a round closes the applications that did not lead to a place are kept.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)], verbose_name='Keep unsuccessful applications for (months)'),
        ),
    ]
