# Generated by Django 5.2.17 on 2026-09-22 03:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('employees', '0002_initial'),
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='First day of the salary month')),
                ('basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='employees.employee')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'ordering': ['-month', 'employee__employee_id'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'month'), name='one_payroll_per_employee_month')],
            },
        ),
    ]
