# Generated by Django 5.2.17 on 2026-09-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_period_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual journal'), ('fee', 'Fee payment'), ('expense', 'Expense'), ('income', 'Other income'), ('salary', 'Salary'), ('reversal', 'Reversal'), ('opening', 'Opening balance'), ('admission', 'Application fee')], default='manual', max_length=10),
        ),
    ]
