# Generated by Django 5.2.17 on 2026-09-21 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('fees', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='income_account',
            field=models.ForeignKey(blank=True, help_text='Income account credited when this fee is collected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_categories', to='finance.account'),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school'),
        ),
        migrations.AddField(
            model_name='feeconcession',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Blank = applies to all categories', null=True, on_delete=django.db.models.deletion.CASCADE, to='fees.feecategory'),
        ),
        migrations.AddField(
            model_name='feeconcession',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school'),
        ),
    ]
