# Generated by Django 5.2.17 on 2026-09-21 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_initial'),
        ('core', '0002_initial'),
        ('fees', '0003_initial'),
        ('finance', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feeinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='students.student'),
        ),
        migrations.AddField(
            model_name='feeinvoiceitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fees.feecategory'),
        ),
        migrations.AddField(
            model_name='feeinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feeinvoice'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.feeinvoice'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payment', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structures', to='fees.feecategory'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.classlevel'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school'),
        ),
        migrations.AddConstraint(
            model_name='feecategory',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_fee_category_per_school'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.UniqueConstraint(fields=('school', 'invoice_no'), name='unique_invoice_no_per_school'),
        ),
        migrations.AddConstraint(
            model_name='feepayment',
            constraint=models.UniqueConstraint(fields=('school', 'receipt_no'), name='unique_receipt_no_per_school'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('academic_year', 'class_level', 'category'), name='unique_fee_structure'),
        ),
    ]
