# Generated by Django 5.2.17 on 2026-09-22 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_initial'),
        ('core', '0002_initial'),
        ('fees', '0004_initial'),
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('month__isnull', False)), fields=('enrollment', 'month'), name='one_invoice_per_enrollment_month'),
        ),
    ]
