# Generated by Django 5.2.17 on 2026-09-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_feeinvoice_one_invoice_per_enrollment_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeconcession',
            options={'ordering': ['student__student_id', 'category__name']},
        ),
    ]
