# Generated by Django 5.2.17 on 2026-09-24 00:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_list_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT added to this fee, in percent. Leave at 0 unless your tax adviser confirms VAT applies: whether it does for school tuition has been disputed and ruled on before.', max_digits=5, verbose_name='VAT %'),
        ),
        migrations.AddField(
            model_name='feeinvoiceitem',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer / cheque'), ('mobile', 'Mobile banking (bKash / Nagad / Rocket)'), ('online', 'Paid online (payment gateway)')], default='cash', max_length=10),
        ),
    ]
