# Generated by Django 5.2.17 on 2026-09-24 15:25

import admissions.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0009_co_teachers'),
        ('core', '0019_school_admissions_keep_months'),
        ('finance', '0005_alter_journalentry_source'),
        ('students', '0009_studentship_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Admission 2027', max_length=120)),
                ('opens_on', models.DateField()),
                ('closes_on', models.DateField()),
                ('instructions', models.TextField(blank=True, help_text='Shown to families above the form.')),
                ('instructions_bn', models.TextField(blank=True, verbose_name='Instructions (Bangla)')),
                ('application_fee', models.DecimalField(decimal_places=2, default=0, help_text='Paid at the school office. Zero for no fee.', max_digits=10)),
                ('fee_before_assessment', models.BooleanField(default=True, help_text='Families pay the fee before the test or interview.')),
                ('offer_days', models.PositiveSmallIntegerField(default=7, help_text='Days a family has to accept an offered place before it lapses.')),
                ('sibling_rule', models.CharField(choices=[('none', 'Not considered'), ('tie_break', 'Breaks a tie in the merit list'), ('priority', 'Offered first among those who pass')], default='tie_break', max_length=10)),
                ('is_published', models.BooleanField(default=False, help_text='Families see the round only once it is published, and apply only while it is open.')),
                ('academic_year', models.ForeignKey(help_text='The year the children will join.', on_delete=django.db.models.deletion.PROTECT, related_name='admission_rounds', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'ordering': ['-opens_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_generation', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('offered', 'Offered a place'), ('waitlisted', 'On the waiting list'), ('not_offered', 'Not offered a place'), ('lapsed', 'Offer lapsed'), ('accepted', 'Place accepted'), ('offer_declined', 'Place declined'), ('withdrawn', 'Withdrawn'), ('enrolled', 'Enrolled')], default='submitted', max_length=16)),
                ('channel', models.CharField(choices=[('online', 'Online'), ('office', 'At the office')], default='online', max_length=8)),
                ('heard_from', models.CharField(blank=True, choices=[('sibling', 'A brother or sister studies here'), ('family', 'Family or friends'), ('website', "The school's website"), ('social', 'Social media'), ('newspaper', 'A newspaper or poster'), ('event', 'An open day or event'), ('other', 'Somewhere else')], max_length=10)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('name_bn', models.CharField(blank=True, max_length=200, verbose_name='Name (Bangla)')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('religion', models.CharField(blank=True, max_length=30)),
                ('birth_registration_no', models.CharField(blank=True, max_length=17)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('previous_class', models.CharField(blank=True, max_length=50)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_relation', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('grandparent', 'Grandparent'), ('sibling', 'Brother or sister'), ('uncle_aunt', 'Uncle or aunt'), ('other', 'Other')], max_length=15)),
                ('guardian_phone', models.CharField(max_length=25)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_occupation', models.CharField(blank=True, max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=150, verbose_name="Father's name")),
                ('mother_name', models.CharField(blank=True, max_length=150, verbose_name="Mother's name")),
                ('address', models.TextField(blank=True)),
                ('sibling_claimed', models.BooleanField(default=False)),
                ('sibling_details', models.CharField(blank=True, help_text='The name and class the family gave.', max_length=200)),
                ('sibling_verified_at', models.DateTimeField(blank=True, null=True)),
                ('consent_version', models.CharField(max_length=20)),
                ('consent_at', models.DateTimeField()),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('age_override_reason', models.CharField(blank=True, max_length=200)),
                ('fee_waived_reason', models.CharField(blank=True, max_length=200)),
                ('fee_waived_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=300)),
                ('offer_expires_on', models.DateField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('merit_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('fee_waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('possible_duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possible_duplicates', to='admissions.application')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('sibling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sibling_applications', to='students.student')),
                ('sibling_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='students.student')),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
                'permissions': [('decide_application', 'Can offer, wait-list or turn down an application')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('birth_certificate', 'Birth registration certificate'), ('photo', 'Recent photo of the child'), ('report_card', 'Last report card'), ('transfer_certificate', 'Transfer certificate'), ('guardian_nid', "Guardian's national ID card"), ('other', 'Other document')], max_length=24)),
                ('file', models.FileField(max_length=200, upload_to=admissions.models.document_path)),
                ('file_kind', models.CharField(max_length=8)),
                ('size', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting to be checked'), ('accepted', 'Accepted'), ('rejected', 'Not accepted')], default='waiting', max_length=10)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=200)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.application')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Empty when the family uploaded it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('status', 'Status'), ('note', 'Note'), ('document', 'Document'), ('payment', 'Payment'), ('link', 'Private link'), ('sibling', 'Sibling'), ('details', 'Details')], max_length=10)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(blank=True, max_length=16)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='admissions.application')),
                ('by', models.ForeignKey(blank=True, help_text='Empty when the family did it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_no', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer / cheque'), ('mobile', 'Mobile banking (bKash / Nagad / Rocket)')], default='cash', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Transaction ID / cheque no', max_length=100)),
                ('date', models.DateField()),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=200)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='admissions.application')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_payment', to='finance.journalentry')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RoundClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seats', models.PositiveSmallIntegerField()),
                ('assessment', models.CharField(choices=[('none', 'No test or interview'), ('test', 'Admission test'), ('interview', 'Interview'), ('both', 'Admission test and interview')], default='none', max_length=10)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pass_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('born_on_or_after', models.DateField(blank=True, null=True)),
                ('born_on_or_before', models.DateField(blank=True, null=True)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('admission_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='admissions.admissionround')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.classlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'ordering': ['class_level__order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='round_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='admissions.roundclass'),
        ),
        migrations.AddConstraint(
            model_name='admissionround',
            constraint=models.CheckConstraint(condition=models.Q(('closes_on__gte', models.F('opens_on'))), name='round_closes_after_it_opens'),
        ),
        migrations.AddConstraint(
            model_name='applicationpayment',
            constraint=models.UniqueConstraint(fields=('school', 'receipt_no'), name='unique_application_receipt_no'),
        ),
        migrations.AddConstraint(
            model_name='applicationpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='application_payment_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='roundclass',
            constraint=models.UniqueConstraint(fields=('admission_round', 'class_level'), name='one_round_class_per_level'),
        ),
        migrations.AddConstraint(
            model_name='roundclass',
            constraint=models.CheckConstraint(condition=models.Q(('born_on_or_after__isnull', True), ('born_on_or_before__isnull', True), ('born_on_or_before__gte', models.F('born_on_or_after')), _connector='OR'), name='round_class_birth_window_in_order'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('school', 'reference'), name='unique_application_reference'),
        ),
    ]
