# Generated by Django 5.2.17 on 2026-09-24 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('core', '0019_school_admissions_keep_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('test', 'Admission test'), ('interview', 'Interview')], max_length=10)),
                ('starts_at', models.DateTimeField()),
                ('venue', models.CharField(max_length=150)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, help_text='Empty for no limit.', null=True)),
                ('note', models.CharField(blank=True, help_text='Shown to families, e.g. what to bring.', max_length=300)),
                ('round_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='admissions.roundclass')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attended', models.BooleanField(blank=True, help_text='Empty until the sitting is recorded.', null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.CharField(blank=True, help_text='For staff only.', max_length=300)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='admissions.application')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='admissions.assessment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'ordering': ['assessment__starts_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'application'), name='one_result_per_sitting'), models.CheckConstraint(condition=models.Q(('score__isnull', True), ('score__gte', 0), _connector='OR'), name='score_not_negative')],
            },
        ),
    ]
