# Generated by Django 5.2.17 on 2026-09-23 00:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_deactivatable'),
        ('core', '0006_period_lock'),
        ('downloads', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Plain text. It is shown as written, never as HTML.')),
                ('audience', models.CharField(choices=[('everyone', 'Everyone'), ('staff', 'Teachers & staff only'), ('students', 'Students & guardians'), ('public', 'Public (no login required)')], default='everyone', max_length=10)),
                ('publish_at', models.DateField(default=django.utils.timezone.localdate)),
                ('expires_at', models.DateField(blank=True, help_text='After this date it drops off the boards.', null=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Keep at the top while it matters.')),
                ('class_levels', models.ManyToManyField(blank=True, help_text='Leave empty for all classes.', related_name='notices', to='academics.classlevel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'ordering': ['-is_pinned', '-publish_at', '-id'],
            },
        ),
    ]
