# Generated by Django 5.2.17 on 2026-09-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaditem',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Everyone at the school'), ('staff', 'Teachers and staff only'), ('students', 'Students and guardians'), ('public', 'Public, no sign-in needed')], default='everyone', max_length=10),
        ),
        migrations.AlterField(
            model_name='notice',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Everyone at the school'), ('staff', 'Teachers and staff only'), ('students', 'Students and guardians'), ('public', 'Public, no sign-in needed')], default='everyone', max_length=10),
        ),
    ]
