# Generated by Django 5.2.17 on 2026-09-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notifications'),
        ('messaging', '0003_alter_smsmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='dedupe_key',
            field=models.CharField(blank=True, help_text='Identifies an automatic message so the same event never queues twice.', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='smsmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('school', 'dedupe_key'), name='unique_automatic_message_per_event'),
        ),
    ]
