# Generated by Django 5.2.17 on 2026-09-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='When a worker took this message. A stale claim is reclaimed after the timeout.', null=True),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, help_text='Earliest the next delivery attempt may run, so a failing gateway is backed off.', null=True),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='redact_after_send',
            field=models.BooleanField(default=False, help_text='Set on a message whose text is a secret. The body is cleared once delivery ends.'),
        ),
    ]
