# Generated by Django 5.2.17 on 2026-09-24 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0009_co_teachers'),
        ('core', '0016_school_modules'),
        ('employees', '0004_deactivatable'),
        ('students', '0009_studentship_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('purpose', models.CharField(blank=True, help_text='What this practises, in a line. Families see it first.', max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('practice', 'Practice'), ('reading', 'Reading'), ('revision', 'Revision'), ('project', 'Project'), ('preparation', 'Preparation'), ('other', 'Other')], default='practice', max_length=12)),
                ('hand_in', models.CharField(choices=[('in_class', 'Checked in class'), ('online', 'Handed in online'), ('none', 'Nothing to hand in')], default='in_class', max_length=10)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=20, help_text='About how long a typical student needs.')),
                ('marking', models.CharField(choices=[('none', 'No mark'), ('marks', 'Marks'), ('grade', 'Grade'), ('comment', 'Comment only')], default='none', max_length=10)),
                ('max_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('marks_visible', models.BooleanField(default=True, help_text='Show the mark to the student and family once the work is returned.')),
                ('allow_late', models.BooleanField(default=True, help_text='Work may still be handed in after the due time.')),
                ('selected_only', models.BooleanField(default=False, help_text='Set for chosen students only, not the whole section.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=10)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_tasks', to='academics.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_tasks', to='academics.classlevel')),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='homework.task')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_tasks', to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_tasks', to='employees.employee')),
            ],
            options={
                'ordering': ['-publish_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TaskSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_at', models.DateTimeField()),
                ('due_on', models.DateField(editable=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_targets', to='academics.section')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='homework.task')),
            ],
            options={
                'ordering': ['due_at', 'section__name'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Not checked yet'), ('done', 'Done'), ('partial', 'Partly done'), ('not_done', 'Not done'), ('absent', 'Absent'), ('excused', 'Excused')], default='pending', max_length=10)),
                ('source', models.CharField(blank=True, choices=[('', '—'), ('online', 'Handed in online'), ('family', 'Ticked done at home'), ('teacher', 'Checked by the teacher')], default='', max_length=10)),
                ('late', models.BooleanField(default=False)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('handed_in_at', models.DateTimeField(blank=True, null=True)),
                ('by_guardian', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('feedback', models.CharField(blank=True, max_length=1000)),
                ('reason', models.CharField(blank=True, help_text='Why the student was excused.', max_length=150)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('redo_requested', models.BooleanField(default=False)),
                ('extended_to', models.DateTimeField(blank=True, help_text='A later due time for this student only.', null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='students.enrollment')),
                ('handed_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.task')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.tasksection')),
            ],
            options={
                'ordering': ['target__section__name', 'enrollment__roll_number'],
            },
        ),
        migrations.CreateModel(
            name='DailyLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minutes', models.PositiveSmallIntegerField()),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_limits', to='academics.classlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'ordering': ['class_level__order'],
                'constraints': [models.UniqueConstraint(fields=('school', 'class_level'), name='one_homework_limit_per_class'), models.CheckConstraint(condition=models.Q(('minutes__gte', 1), ('minutes__lte', 600)), name='homework_limit_in_range')],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['school', 'academic_year', 'status'], name='homework_ta_school__0082cd_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['teacher', 'status'], name='homework_ta_teacher_b6f558_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_minutes__gte', 1), ('estimated_minutes__lte', 300)), name='homework_minutes_in_range'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('marking', 'marks'), ('max_marks__gt', 0)), models.Q(models.Q(('marking', 'marks'), _negated=True), ('max_marks__isnull', True)), _connector='OR'), name='homework_max_marks_only_when_marked'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), ('publish_at__isnull', False), _connector='OR'), name='homework_published_has_a_time'),
        ),
        migrations.AddIndex(
            model_name='tasksection',
            index=models.Index(fields=['section', 'due_on'], name='homework_ta_section_a85d75_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasksection',
            constraint=models.UniqueConstraint(fields=('task', 'section'), name='one_target_per_task_section'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['enrollment', 'status'], name='homework_su_enrollm_7e58a5_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['target', 'status'], name='homework_su_target__9ea0f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('task', 'enrollment'), name='one_submission_per_task_student'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('mark__isnull', True), ('mark__gte', 0), _connector='OR'), name='homework_mark_not_negative'),
        ),
    ]
