# Generated by Django 5.2.17 on 2026-09-24 09:43

import core.models
import django.db.models.deletion
import homework.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_school_homework_files_months'),
        ('homework', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=200, upload_to=homework.models.hand_in_path)),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('jpeg', 'Photo'), ('docx', 'Word document')], max_length=8)),
                ('size', models.PositiveIntegerField()),
                ('page', models.PositiveSmallIntegerField(default=1)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='homework.submission')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['attempt', 'page', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TaskResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(blank=True, max_length=200, upload_to=homework.models.resource_path)),
                ('kind', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('jpeg', 'Photo'), ('docx', 'Word document')], max_length=8)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('url', core.models.HttpsURLField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='homework.task')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('file', ''), models.Q(('url', ''), _negated=True)), models.Q(models.Q(('file', ''), _negated=True), ('url', '')), _connector='OR'), name='homework_resource_is_a_file_or_a_link')],
            },
        ),
    ]
