# Generated by Django 5.2.17 on 2026-09-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Clear this to retire the record without losing the history that uses it.'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Clear this to retire the record without losing the history that uses it.'),
        ),
    ]
