# Generated by Django 5.2.17 on 2026-09-25 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_school_admissions_keep_months'),
        ('timetable', '0002_deactivatable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodDayTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(6, 'Saturday'), (7, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('not_held', models.BooleanField(default=False)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_times', to='timetable.period')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'ordering': ['weekday', 'period__order'],
                'constraints': [models.UniqueConstraint(fields=('period', 'weekday'), name='one_timing_per_period_day')],
            },
        ),
    ]
