# Generated by Django 5.2.17 on 2026-09-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_school_admissions_keep_months'),
        ('timetable', '0003_perioddaytime'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='period',
            name='unique_period_order_per_school',
        ),
        migrations.AddField(
            model_name='period',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('day', 'Day'), ('evening', 'Evening')], help_text='Leave blank for the default schedule. Choose a shift for its own periods and breaks.', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('school', 'shift', 'order'), name='unique_period_order_per_shift'),
        ),
    ]
