# Generated by Django 5.2.17 on 2026-09-26 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_section_default_room'),
        ('core', '0019_school_admissions_keep_months'),
        ('timetable', '0004_remove_period_unique_period_order_per_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionRoomChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, help_text='For example, classroom maintenance.', max_length=200)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_changes', to='timetable.room')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_changes', to='academics.section')),
            ],
            options={
                'verbose_name': 'Temporary classroom change',
                'verbose_name_plural': 'Temporary classroom changes',
                'ordering': ['-start_date', 'section__class_level__order', 'section__name'],
            },
        ),
    ]
