# Generated by Django 5.2.17 on 2026-09-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectteacher',
            options={'ordering': ['section__class_level__order', 'section__name', 'subject__name']},
        ),
    ]
