# Generated by Django 5.2.17 on 2026-09-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_list_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Clear this to retire the record without losing the history that uses it.'),
        ),
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Clear this to retire the record without losing the history that uses it.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Clear this to retire the record without losing the history that uses it.'),
        ),
    ]
