# Generated by Django 5.2.17 on 2026-09-23 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_deactivatable'),
        ('core', '0010_school_settings_for_board_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='assessment_system',
            field=models.CharField(blank=True, choices=[('own', "School's own rules (percentage and grade)"), ('national', 'Bangladesh national curriculum (SSC board rules)')], help_text="Leave blank to follow the school's setting.", max_length=10),
        ),
        migrations.AddField(
            model_name='section',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('day', 'Day'), ('evening', 'Evening')], help_text='For a school that runs more than one shift.', max_length=10),
        ),
        migrations.AddField(
            model_name='section',
            name='version',
            field=models.CharField(blank=True, choices=[('bangla', 'Bangla medium'), ('english', 'English version')], help_text='Bangla medium or English version of the national curriculum.', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='combines_into',
            field=models.ForeignKey(blank=True, help_text='For a subject examined in two papers: the subject both papers count towards. Bangla 1st paper and Bangla 2nd paper both count towards Bangla, and are graded together.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_bn',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Bangla)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='religion',
            field=models.CharField(blank=True, choices=[('islam', 'Islam'), ('hinduism', 'Hinduism'), ('buddhism', 'Buddhism'), ('christianity', 'Christianity'), ('other', 'Other')], help_text='For a religion paper: only students of this religion sit it.', max_length=30),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, help_text='The board subject code, e.g. 101 for Bangla 1st paper.', max_length=20),
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(blank=True, choices=[('science', 'Science'), ('business', 'Business Studies'), ('humanities', 'Humanities')], help_text='Blank means every group.', max_length=12)),
                ('kind', models.CharField(choices=[('compulsory', 'Compulsory'), ('choice', 'Choice (taken as a main or a 4th subject)')], default='compulsory', max_length=12)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.classlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.subject')),
            ],
            options={
                'ordering': ['class_level__order', 'group', 'kind', 'subject__code', 'subject__name'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'class_level', 'subject', 'group'), name='unique_class_subject_per_group')],
            },
        ),
    ]
