# Generated by Django 5.2.17 on 2026-09-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_subject_plan_and_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevel',
            name='assessment_system',
            field=models.CharField(blank=True, choices=[('own', "School's own rules (percentage and grade)"), ('national', 'Bangladesh national curriculum (SSC board rules)'), ('cambridge', 'Cambridge (IGCSE, O Level, AS and A Level)'), ('edexcel', 'Pearson Edexcel (International GCSE, International AS and A Level)'), ('ib_myp', 'IB Middle Years Programme (criteria to grades 1-7)')], help_text="Leave blank to follow the school's setting.", max_length=10),
        ),
    ]
