# Generated by Django 5.2.17 on 2026-09-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_more_rulebooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='ib_core',
            field=models.CharField(blank=True, choices=[('tok', 'Theory of Knowledge'), ('ee', 'Extended Essay'), ('cas', 'CAS')], help_text="For the IB Diploma core. TOK and the Extended Essay are graded A to E; CAS is complete when its mark reaches the paper's pass mark.", max_length=3, verbose_name='IB core'),
        ),
        migrations.AddField(
            model_name='subject',
            name='ib_level',
            field=models.CharField(blank=True, choices=[('HL', 'Higher Level'), ('SL', 'Standard Level')], help_text='For IB Diploma subjects. Record Biology HL and Biology SL as two subjects.', max_length=2, verbose_name='IB level'),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='assessment_system',
            field=models.CharField(blank=True, choices=[('own', "School's own rules (percentage and grade)"), ('national', 'Bangladesh national curriculum (SSC board rules)'), ('cambridge', 'Cambridge (IGCSE, O Level, AS and A Level)'), ('edexcel', 'Pearson Edexcel (International GCSE, International AS and A Level)'), ('ib_myp', 'IB Middle Years Programme (criteria to grades 1-7)'), ('ib_dp', 'IB Diploma Programme (grades 1-7, core points, diploma conditions)')], help_text="Leave blank to follow the school's setting.", max_length=10),
        ),
    ]
