# Generated by Django 5.2.17 on 2026-09-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_ib_subject_roles'),
        ('core', '0014_privacy_baseline'),
        ('employees', '0004_deactivatable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subjectteacher',
            name='unique_subject_teacher_per_section',
        ),
        migrations.AddConstraint(
            model_name='subjectteacher',
            constraint=models.UniqueConstraint(fields=('academic_year', 'section', 'subject', 'teacher'), name='unique_subject_teacher_per_section'),
        ),
    ]
