# Generated by Django 5.2.17 on 2026-09-25 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_co_teachers'),
        ('core', '0019_school_admissions_keep_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_date', models.DateField()),
                ('kind', models.CharField(choices=[('lesson', 'Lesson'), ('revision', 'Revision'), ('quiz', 'Quiz planned'), ('class_test', 'Class test planned')], default='lesson', max_length=12)),
                ('unit', models.CharField(blank=True, help_text='Chapter or unit, such as Fractions.', max_length=100)),
                ('topic', models.CharField(help_text='What you plan to teach or assess.', max_length=150)),
                ('learning_goal', models.TextField(blank=True, help_text='What students should be able to do afterward.')),
                ('taught_on', models.DateField(blank=True, help_text='Fill this in after the lesson or activity happens.', null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_plan_items', to='academics.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_plan_items', to='academics.classlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('section', models.ForeignKey(blank=True, help_text='Leave blank to plan for every section in this class.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_plan_items', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_plan_items', to='academics.subject')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_plan_items', to='academics.term')),
            ],
            options={
                'ordering': ['planned_date', 'pk'],
                'indexes': [models.Index(fields=['school', 'academic_year', 'class_level', 'subject', 'planned_date'], name='academics_t_school__936685_idx')],
            },
        ),
    ]
