# Generated by Django 5.2.17 on 2026-09-26 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_teachingplanitem'),
        ('timetable', '0004_remove_period_unique_period_order_per_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='default_room',
            field=models.ForeignKey(blank=True, help_text='The usual classroom for this section. Add rooms under Routine → School days & periods → Rooms first.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_sections', to='timetable.room'),
        ),
    ]
