# Generated by Django 5.2.17 on 2026-09-22 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='created_by_leave',
            field=models.ForeignKey(blank=True, help_text='Set when an approved leave generated this row, so withdrawing the leave removes it again.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_rows', to='attendance.leaverequest'),
        ),
    ]
