# Generated by Django 5.2.17 on 2026-09-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_leave_attendance_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Clear this to retire the record without losing the history that uses it.'),
        ),
    ]
