# Generated by Django 5.2.17 on 2026-09-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_deactivatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='allow_negative',
            field=models.BooleanField(default=False, help_text='Let a request go past the annual entitlement. The balance is then shown as negative.'),
        ),
    ]
