# Generated by Django 5.2.17 on 2026-09-21 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_initial'),
        ('core', '0002_initial'),
        ('examinations', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='academics.classlevel'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='examinations.exam'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school'),
        ),
        migrations.AddField(
            model_name='graderule',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='examinations.gradescale'),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade_scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='examinations.gradescale'),
        ),
        migrations.AddField(
            model_name='mark',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='mark',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mark',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='examinations.examschedule'),
        ),
        migrations.AddField(
            model_name='mark',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school'),
        ),
        migrations.AddConstraint(
            model_name='examschedule',
            constraint=models.UniqueConstraint(fields=('exam', 'class_level', 'subject'), name='unique_exam_subject_per_class'),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_grade_scale_per_school'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='unique_exam_name_per_year'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('schedule', 'enrollment'), name='one_mark_per_student_paper'),
        ),
    ]
