# Generated by Django 5.2.17 on 2026-09-22 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_initial'),
        ('examinations', '0004_published_mark_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='academics.term'),
        ),
    ]
