# Generated by Django 5.2.17 on 2026-09-23 04:39

import django.db.models.deletion
import importlib

from django.db import migrations, models

# The published-marks lock is a set of triggers that name the exam and schedule tables.
# SQLite rebuilds a table to add a column, and a trigger pointing at a table mid-rebuild
# fails. So the lock is lifted for the length of this migration and reinstalled after it,
# exactly as it was defined, from the migration that created it.
_lock = importlib.import_module("examinations.migrations.0004_published_mark_lock")


def lift_lock(apps, schema_editor):
    _lock.remove(apps, schema_editor)


def restore_lock(apps, schema_editor):
    _lock.install(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_school_settings_for_board_rules'),
        ('examinations', '0005_exam_term'),
    ]

    operations = [
        migrations.RunPython(lift_lock, restore_lock),
        migrations.AddField(
            model_name='exam',
            name='assessment_system',
            field=models.CharField(blank=True, choices=[('own', "School's own rules (percentage and grade)"), ('national', 'Bangladesh national curriculum (SSC board rules)')], help_text="Leave blank to follow each class's setting. Set it for an internal test, such as a class test, that should not use the board's GPA rules.", max_length=10),
        ),
        migrations.AddField(
            model_name='mark',
            name='component_marks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PaperComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='Short key, e.g. cq, mcq, practical.', max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('full_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pass_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='examinations.examschedule')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'code'), name='unique_component_per_paper')],
            },
        ),
        migrations.RunPython(restore_lock, lift_lock),
    ]
