# Generated by Django 5.2.17 on 2026-09-23 05:05

import django.db.models.deletion
import importlib

from django.db import migrations, models

# SQLite rebuilds the exam and schedule tables to add these columns, and the published-marks
# lock triggers name those tables, so the lock is lifted for this migration and restored after.
_lock = importlib.import_module("examinations.migrations.0004_published_mark_lock")


def lift_lock(apps, schema_editor):
    _lock.remove(apps, schema_editor)


def restore_lock(apps, schema_editor):
    _lock.install(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0006_paper_components_and_rules'),
    ]

    operations = [
        migrations.RunPython(lift_lock, restore_lock),
        migrations.AddField(
            model_name='exam',
            name='show_rank',
            field=models.BooleanField(blank=True, help_text="Leave blank for the rulebook's usual practice: positions for national-curriculum and the school's own rules, none for Cambridge, Edexcel and IB.", null=True, verbose_name='Show positions'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='grade_scale',
            field=models.ForeignKey(blank=True, help_text="Leave blank to use the exam's scale. Set it for a subject graded on another board's scale, for example Edexcel 9-1 Mathematics in a Cambridge year.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='examinations.gradescale'),
        ),
        migrations.AddField(
            model_name='papercomponent',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percent of the paper this part is worth, when parts are scaled rather than added: Cambridge Paper 2 at 40% from 80 raw marks, for example. Leave every part blank to add the raw marks.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='assessment_system',
            field=models.CharField(blank=True, choices=[('own', "School's own rules (percentage and grade)"), ('national', 'Bangladesh national curriculum (SSC board rules)'), ('cambridge', 'Cambridge (IGCSE, O Level, AS and A Level)'), ('edexcel', 'Pearson Edexcel (International GCSE, International AS and A Level)'), ('ib_myp', 'IB Middle Years Programme (criteria to grades 1-7)')], help_text="Leave blank to follow each class's setting. Set it for an internal test, such as a class test, that should not use the board's GPA rules.", max_length=10),
        ),
        migrations.RunPython(restore_lock, lift_lock),
    ]
