# Generated by Django 5.2.17 on 2026-09-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0007_rulebook_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='assessment_system',
            field=models.CharField(blank=True, choices=[('own', "School's own rules (percentage and grade)"), ('national', 'Bangladesh national curriculum (SSC board rules)'), ('cambridge', 'Cambridge (IGCSE, O Level, AS and A Level)'), ('edexcel', 'Pearson Edexcel (International GCSE, International AS and A Level)'), ('ib_myp', 'IB Middle Years Programme (criteria to grades 1-7)'), ('ib_dp', 'IB Diploma Programme (grades 1-7, core points, diploma conditions)')], help_text="Leave blank to follow each class's setting. Set it for an internal test, such as a class test, that should not use the board's GPA rules.", max_length=10),
        ),
    ]
