# Generated by Django 5.2.17 on 2026-09-23 05:35

import importlib

from django.db import migrations, models

# SQLite rebuilds the schedule table to add this column, and the published-marks lock triggers
# name it, so the lock is lifted for this migration and restored after.
_lock = importlib.import_module("examinations.migrations.0004_published_mark_lock")


def lift_lock(apps, schema_editor):
    _lock.remove(apps, schema_editor)


def restore_lock(apps, schema_editor):
    _lock.install(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0008_ib_diploma'),
    ]

    operations = [
        migrations.RunPython(lift_lock, restore_lock),
        migrations.AddField(
            model_name='examschedule',
            name='max_grade',
            field=models.CharField(blank=True, help_text='The highest grade this paper can earn, for a tiered entry: C for Cambridge IGCSE Core, 5 for Core on a 9-1 scale. Leave blank for no cap.', max_length=5),
        ),
        migrations.RunPython(restore_lock, lift_lock),
    ]
