# Generated by Django 5.2.17 on 2026-09-23 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_ib_subject_roles'),
        ('core', '0012_ib_diploma'),
        ('examinations', '0009_paper_max_grade'),
        ('students', '0005_board_identity_and_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('predicted', 'Predicted grade'), ('forecast', 'Forecast grade'), ('target', 'Target grade')], max_length=10)),
                ('grade', models.CharField(max_length=5)),
                ('as_of', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='students.enrollment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='academics.subject')),
            ],
            options={
                'ordering': ['-as_of', '-id'],
                'indexes': [models.Index(fields=['enrollment', 'subject', 'kind'], name='examination_enrollm_e66ebd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResultComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effort', models.CharField(blank=True, help_text='Effort grade, or approaches to learning in an IB class, as the school reports it.', max_length=20)),
                ('comment', models.TextField(blank=True, max_length=600)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_comments', to='students.enrollment')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='examinations.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='academics.subject')),
                ('written_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('subject__isnull', False)), fields=('exam', 'enrollment', 'subject'), name='one_subject_comment_per_student'), models.UniqueConstraint(condition=models.Q(('subject__isnull', True)), fields=('exam', 'enrollment'), name='one_overall_comment_per_student')],
            },
        ),
    ]
