# Generated by Django 5.2.17 on 2026-09-23 10:15

import importlib

from django.db import migrations, models

# SQLite rebuilds the marks table to add this column, and the published-marks lock triggers
# name it, so the lock is lifted for this migration and restored after.
_lock = importlib.import_module("examinations.migrations.0004_published_mark_lock")


def lift_lock(apps, schema_editor):
    _lock.remove(apps, schema_editor)


def restore_lock(apps, schema_editor):
    _lock.install(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0012_series_entries_official_results'),
    ]

    operations = [
        migrations.RunPython(lift_lock, restore_lock),
        migrations.AddField(
            model_name='mark',
            name='is_exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(restore_lock, lift_lock),
    ]
