# Generated by Django 5.2.17 on 2026-09-23 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ib_diploma'),
        ('examinations', '0014_combined_results'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seriescandidate',
            name='certificate_name',
            field=models.CharField(blank=True, help_text="The name as it should print on the certificate, up to 60 characters. Blank uses the student's name.", max_length=60),
        ),
        migrations.CreateModel(
            name='AccessArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('extra_time', 'Extra time'), ('reader', 'Reader or computer reader'), ('scribe', 'Scribe or word processor'), ('room', 'Separate room'), ('breaks', 'Supervised rest breaks'), ('other', 'Other')], max_length=12)),
                ('details', models.CharField(blank=True, help_text='e.g. 25% extra time in written papers.', max_length=200)),
                ('evidence', models.CharField(blank=True, help_text='What supports it; keep the documents offline.', max_length=200)),
                ('consent_on', models.DateField(blank=True, help_text='When the guardian consented to the application.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Being prepared'), ('applied', 'Applied for'), ('approved', 'Approved by the body'), ('refused', 'Refused by the body')], default='draft', max_length=10)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_arrangements', to='examinations.seriescandidate')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'ordering': ['candidate__candidate_number', 'kind'],
            },
        ),
    ]
