# Generated by Django 5.2.17 on 2026-09-24 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_register_policy'),
        ('examinations', '0015_candidate_data_and_access_arrangements'),
        ('students', '0009_studentship_certificate'),
        ('timetable', '0002_deactivatable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('mix_classes', models.BooleanField(default=True, help_text='Seat students of different classes side by side, so neighbours sit different papers.')),
                ('seats_per_room', models.PositiveSmallIntegerField(blank=True, help_text='At most this many in any room, when exam seating is sparser than lessons.', null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_plans', to='examinations.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_seats', to='students.enrollment')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_seats', to='timetable.room')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='examinations.seatplan')),
            ],
            options={
                'ordering': ['room__name', 'number'],
            },
        ),
        migrations.AddConstraint(
            model_name='seatplan',
            constraint=models.UniqueConstraint(fields=('exam', 'date', 'start_time'), name='one_seat_plan_per_sitting'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('plan', 'enrollment'), name='one_seat_per_candidate_per_sitting'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('plan', 'room', 'number'), name='one_candidate_per_seat'),
        ),
    ]
